// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: protobuf/pb/greet.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GreetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MyName string `protobuf:"bytes,1,opt,name=my_name,json=myName,proto3" json:"my_name,omitempty"`
	Msg    string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *GreetReq) Reset() {
	*x = GreetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_pb_greet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GreetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetReq) ProtoMessage() {}

func (x *GreetReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_pb_greet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetReq.ProtoReflect.Descriptor instead.
func (*GreetReq) Descriptor() ([]byte, []int) {
	return file_protobuf_pb_greet_proto_rawDescGZIP(), []int{0}
}

func (x *GreetReq) GetMyName() string {
	if x != nil {
		return x.MyName
	}
	return ""
}

func (x *GreetReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GreetResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *GreetResp) Reset() {
	*x = GreetResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_pb_greet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GreetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetResp) ProtoMessage() {}

func (x *GreetResp) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_pb_greet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetResp.ProtoReflect.Descriptor instead.
func (*GreetResp) Descriptor() ([]byte, []int) {
	return file_protobuf_pb_greet_proto_rawDescGZIP(), []int{1}
}

func (x *GreetResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_protobuf_pb_greet_proto protoreflect.FileDescriptor

var file_protobuf_pb_greet_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x70, 0x62, 0x2f, 0x67, 0x72,
	0x65, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x35, 0x0a, 0x08, 0x47, 0x72, 0x65,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x22, 0x1d, 0x0a, 0x09, 0x47, 0x72, 0x65, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32,
	0x25, 0x0a, 0x03, 0x46, 0x6f, 0x6f, 0x12, 0x1e, 0x0a, 0x05, 0x47, 0x72, 0x65, 0x65, 0x74, 0x12,
	0x09, 0x2e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x0a, 0x2e, 0x47, 0x72, 0x65,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_pb_greet_proto_rawDescOnce sync.Once
	file_protobuf_pb_greet_proto_rawDescData = file_protobuf_pb_greet_proto_rawDesc
)

func file_protobuf_pb_greet_proto_rawDescGZIP() []byte {
	file_protobuf_pb_greet_proto_rawDescOnce.Do(func() {
		file_protobuf_pb_greet_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_pb_greet_proto_rawDescData)
	})
	return file_protobuf_pb_greet_proto_rawDescData
}

var file_protobuf_pb_greet_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_pb_greet_proto_goTypes = []interface{}{
	(*GreetReq)(nil),  // 0: GreetReq
	(*GreetResp)(nil), // 1: GreetResp
}
var file_protobuf_pb_greet_proto_depIdxs = []int32{
	0, // 0: Foo.Greet:input_type -> GreetReq
	1, // 1: Foo.Greet:output_type -> GreetResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_pb_greet_proto_init() }
func file_protobuf_pb_greet_proto_init() {
	if File_protobuf_pb_greet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_pb_greet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GreetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_pb_greet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GreetResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_pb_greet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_pb_greet_proto_goTypes,
		DependencyIndexes: file_protobuf_pb_greet_proto_depIdxs,
		MessageInfos:      file_protobuf_pb_greet_proto_msgTypes,
	}.Build()
	File_protobuf_pb_greet_proto = out.File
	file_protobuf_pb_greet_proto_rawDesc = nil
	file_protobuf_pb_greet_proto_goTypes = nil
	file_protobuf_pb_greet_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FooClient is the client API for Foo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FooClient interface {
	Greet(ctx context.Context, in *GreetReq, opts ...grpc.CallOption) (*GreetResp, error)
}

type fooClient struct {
	cc grpc.ClientConnInterface
}

func NewFooClient(cc grpc.ClientConnInterface) FooClient {
	return &fooClient{cc}
}

func (c *fooClient) Greet(ctx context.Context, in *GreetReq, opts ...grpc.CallOption) (*GreetResp, error) {
	out := new(GreetResp)
	err := c.cc.Invoke(ctx, "/Foo/Greet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FooServer is the server API for Foo service.
type FooServer interface {
	Greet(context.Context, *GreetReq) (*GreetResp, error)
}

// UnimplementedFooServer can be embedded to have forward compatible implementations.
type UnimplementedFooServer struct {
}

func (*UnimplementedFooServer) Greet(context.Context, *GreetReq) (*GreetResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Greet not implemented")
}

func RegisterFooServer(s *grpc.Server, srv FooServer) {
	s.RegisterService(&_Foo_serviceDesc, srv)
}

func _Foo_Greet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FooServer).Greet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Foo/Greet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FooServer).Greet(ctx, req.(*GreetReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Foo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Foo",
	HandlerType: (*FooServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greet",
			Handler:    _Foo_Greet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/pb/greet.proto",
}
